$(document).ready(function(){
	$("#educatorForm").hide();
	$("#educator").click(function(){
		$("#educatorForm").toggle();
	});
	$("#studentForm").hide();
	$("#student").click(function(){
		$("#studentForm").toggle();
	});
});